### ISSUE TITLE
Question on Package Information

### ISSUE THREAD

**Issue by MRvra-MSFT** [LazaUK/AOAI-LangChain-Milvus#1]
May you share the version information of each package used in the requirements file? Thank you!

**Comment by LazaUK** [comment]
Because of the last week's release of openai v1.x package, unfortunately it broke compatibility with the earlier versions of langchain packages. Just updated requirements.txt with a preset versions, although it's probably not a Best Practice 🙂.

**Comment by LazaUK** [comment]
These are the working versions. I'll remove their explicit references from the requirements.txt now, as it may introduce potential security issues if any vulnerabilities found in those versions in the future.

pymilvus==2.3.2
pypdf==3.17.0
langchain==0.0.253
openai==0.28.1
tiktoken==0.3.3

**Comment by MRvra-MSFT** [comment]
Thank you, @LazaUK!
